package core;

import java.util.HashMap;
import java.util.Map;

import static core.Constants.CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER;
import static core.Constants.DISTANCE_BETWEEN_ELEVATORS;

public final class ElevatorPositionHolder {

    public static final Map<Integer, Integer> ELEVATOR_POSITION_BY_ID = new HashMap<Integer, Integer>(){{
        put(1, -CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER);
        put(2, CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER);
        put(3, -CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER -DISTANCE_BETWEEN_ELEVATORS);
        put(4, CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER +DISTANCE_BETWEEN_ELEVATORS );
        put(5, -CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER -DISTANCE_BETWEEN_ELEVATORS * 2);
        put(6, CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER +DISTANCE_BETWEEN_ELEVATORS * 2);
        put(7, -CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER -DISTANCE_BETWEEN_ELEVATORS * 3);
        put(8, CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER + DISTANCE_BETWEEN_ELEVATORS * 3);
        put(9, -CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER -DISTANCE_BETWEEN_ELEVATORS * 4);
        put(10, CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER +DISTANCE_BETWEEN_ELEVATORS * 4);
        put(11, -CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER -DISTANCE_BETWEEN_ELEVATORS * 5);
        put(12, CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER +DISTANCE_BETWEEN_ELEVATORS * 5);
        put(13, -CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER -DISTANCE_BETWEEN_ELEVATORS * 6);
        put(14, CENTRAL_ELEVATOR_DISTANCE_FROM_ENTER +DISTANCE_BETWEEN_ELEVATORS * 6);
    }};

    public static final int ELEVATOR_MIN_POSITION = ELEVATOR_POSITION_BY_ID.get(13);
    public static final int ELEVATOR_MAX_POSITION = ELEVATOR_POSITION_BY_ID.get(14);

}
